import "./globals.css";
import {useRouter} from "next/router";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next pages",
};
export default function RootLayout({ Component, pageProps }) {
  const router = useRouter();
  return (
    <Component {...pageProps} router={router} />
  );
}
