import "./globals.css";
import {useRouter} from "next/router";
import {ThemeProvider as NextThemesProvider} from "next-themes";
import {NextUIProvider} from "@nextui-org/react";
import 'react-toastify/dist/ReactToastify.css';
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next pages",
};
export default function RootLayout({ Component, pageProps }) {
  const router = useRouter();
  return (
      <NextUIProvider>
        <NextThemesProvider attribute="class" defaultTheme="dark">
          <Component {...pageProps} router={router} />
        </NextThemesProvider>
      </NextUIProvider>
  );
}
